### ISSUE TITLE
Mole disappears and game becomes extremely slow once you hit 260 points

### ISSUE THREAD

**Issue by s031068c** [Uni-Breton/Blackblade-Games#7]
Step one: Start game
Step two: Play game until score 260 is reached, Some times doesnt happen at 260 score. When looking at debugging it looks like when updating the Amasks it becomes slow at around the 300 mark.  
Step three: Mole disappears and game becomes extremely slow

Whole game becomes slow, mole disappears and when speed collectibles are picked up it alters the players speed regardless of if its the moles speed that has decreased.

**Comment by c07841c** [comment]
Unable to reproduce the issue, will reopen issue if it reoccurs
